import { ConflictException, Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { and, asc, count, desc, eq, gte, isNull, sql, SQL } from 'drizzle-orm';
import { PaginationParams } from '../../common/query-params';
import { DatabaseService } from '../../db/database.service';
import { inventoryBalances, inventoryLots, inventoryTransactions, items, stockTransferItems, stockTransfers, warehouses, assets } from '../../db/schema';
import { CreateStockTransferDto, UpdateStockTransferDto } from './dto/stock-transfer.dto';
import { WarehousesService } from './warehouses.service';
type Filters = PaginationParams & { farmId: string; clerkUserId: string; status?: 'DRAFT' | 'CONFIRMED' | 'CANCELLED' };
@Injectable() export class StockTransfersService {
  constructor(private readonly databaseService: DatabaseService, private readonly warehousesService: WarehousesService) {}
  async list(f: Filters) { await this.warehousesService.assertFarmAccess(f.farmId, f.clerkUserId, false); const c: SQL[] = [eq(stockTransfers.farmId, f.farmId)]; if (f.status) c.push(eq(stockTransfers.status, f.status)); const w = and(...c); const [data, t] = await Promise.all([this.databaseService.db.select().from(stockTransfers).where(w).orderBy(desc(stockTransfers.createdAt)).limit(f.pageSize).offset(f.offset), this.databaseService.db.select({ value: count() }).from(stockTransfers).where(w)]); const totalItems = Number(t[0]?.value ?? 0); return { data, page: { number: f.page, size: f.pageSize, totalItems, totalPages: Math.ceil(totalItems / f.pageSize) } }; }
  async get(id: string, farmId: string, user: string) { await this.warehousesService.assertFarmAccess(farmId, user, false); return this.withItems(id, farmId); }
  async create(farmId: string, user: string, input: CreateStockTransferDto) { const member = await this.warehousesService.assertFarmAccess(farmId, user, true); this.validateItems(input.items); if (input.fromWarehouseId === input.toWarehouseId) throw new BadRequestException('Source and destination warehouses must differ'); const id = await this.databaseService.db.transaction(async tx => { await this.assertWarehouse(tx, farmId, input.fromWarehouseId); await this.assertWarehouse(tx, farmId, input.toWarehouseId); await this.validateLines(tx, farmId, input.items); const [row] = await tx.insert(stockTransfers).values({ farmId, fromWarehouseId: input.fromWarehouseId, toWarehouseId: input.toWarehouseId, transferCode: input.transferCode, transferDate: input.transferDate, note: input.note, createdByMemberId: member }).returning({ id: stockTransfers.id }); await tx.insert(stockTransferItems).values(input.items.map(x => ({ stockTransferId: row.id, itemId: x.itemId, lotId: x.lotId, assetId: x.assetId, quantity: x.quantity, note: x.note }))); return row.id; }); return this.withItems(id, farmId); }
  async update(id: string, farmId: string, user: string, input: UpdateStockTransferDto) { await this.warehousesService.assertFarmAccess(farmId, user, true); const cur = await this.only(id, farmId); if (cur.status !== 'DRAFT') throw new ConflictException('Only DRAFT transfers can be edited'); const from = input.fromWarehouseId ?? cur.fromWarehouseId; const to = input.toWarehouseId ?? cur.toWarehouseId; if (from === to) throw new BadRequestException('Source and destination warehouses must differ'); await this.databaseService.db.transaction(async tx => { await this.assertWarehouse(tx, farmId, from); await this.assertWarehouse(tx, farmId, to); if (input.items) { this.validateItems(input.items); await this.validateLines(tx, farmId, input.items); await tx.delete(stockTransferItems).where(eq(stockTransferItems.stockTransferId, id)); await tx.insert(stockTransferItems).values(input.items.map(x => ({ stockTransferId: id, itemId: x.itemId, lotId: x.lotId, assetId: x.assetId, quantity: x.quantity, note: x.note }))); } const changes: Partial<typeof stockTransfers.$inferInsert> = {}; for (const k of ['fromWarehouseId','toWarehouseId','transferCode','transferDate','note'] as const) if (input[k] !== undefined) changes[k] = input[k] as never; changes.updatedAt = new Date().toISOString(); await tx.update(stockTransfers).set(changes).where(eq(stockTransfers.id, id)); }); return this.withItems(id, farmId); }
  async cancel(id: string, farmId: string, user: string) { await this.warehousesService.assertFarmAccess(farmId, user, true); const row = await this.only(id, farmId); if (row.status !== 'DRAFT') throw new ConflictException('Only DRAFT transfers can be cancelled'); await this.databaseService.db.update(stockTransfers).set({ status: 'CANCELLED', cancelledAt: new Date().toISOString(), updatedAt: new Date().toISOString() }).where(eq(stockTransfers.id, id)); return this.withItems(id, farmId); }
  async confirm(id: string, farmId: string, user: string) { const member = await this.warehousesService.assertFarmAccess(farmId, user, true); await this.databaseService.db.transaction(async tx => { const row = await this.only(id, farmId); if (row.status === 'CONFIRMED') return; if (row.status !== 'DRAFT') throw new ConflictException('Only DRAFT transfers can be confirmed'); await this.assertWarehouse(tx, farmId, row.fromWarehouseId); await this.assertWarehouse(tx, farmId, row.toWarehouseId); const lines = await tx.select().from(stockTransferItems).where(eq(stockTransferItems.stockTransferId, id)); if (!lines.length) throw new BadRequestException('Transfer must contain at least one item'); for (const line of lines) { const [source] = await tx.select().from(inventoryBalances).where(and(eq(inventoryBalances.farmId, farmId), eq(inventoryBalances.warehouseId, row.fromWarehouseId), eq(inventoryBalances.itemId, line.itemId), line.lotId ? eq(inventoryBalances.lotId, line.lotId) : isNull(inventoryBalances.lotId), gte(inventoryBalances.quantityOnHand, line.quantity))).limit(1); if (!source) throw new ConflictException('Insufficient source inventory'); await tx.update(inventoryBalances).set({ quantityOnHand: sql`${inventoryBalances.quantityOnHand} - ${line.quantity}`, updatedAt: new Date().toISOString() }).where(eq(inventoryBalances.id, source.id)); const [dest] = await tx.select().from(inventoryBalances).where(and(eq(inventoryBalances.farmId, farmId), eq(inventoryBalances.warehouseId, row.toWarehouseId), eq(inventoryBalances.itemId, line.itemId), line.lotId ? eq(inventoryBalances.lotId, line.lotId) : isNull(inventoryBalances.lotId))).limit(1); if (dest) await tx.update(inventoryBalances).set({ quantityOnHand: sql`${inventoryBalances.quantityOnHand} + ${line.quantity}`, updatedAt: new Date().toISOString() }).where(eq(inventoryBalances.id, dest.id)); else await tx.insert(inventoryBalances).values({ farmId, warehouseId: row.toWarehouseId, itemId: line.itemId, lotId: line.lotId, quantityOnHand: line.quantity }); await tx.insert(inventoryTransactions).values([{ farmId, warehouseId: row.fromWarehouseId, itemId: line.itemId, lotId: line.lotId, assetId: line.assetId, transactionType: 'TRANSFER_OUT', quantityChange: `-${line.quantity}`, sourceType: 'STOCK_TRANSFER', sourceId: id, performedByMemberId: member }, { farmId, warehouseId: row.toWarehouseId, itemId: line.itemId, lotId: line.lotId, assetId: line.assetId, transactionType: 'TRANSFER_IN', quantityChange: line.quantity, sourceType: 'STOCK_TRANSFER', sourceId: id, performedByMemberId: member }]); } await tx.update(stockTransfers).set({ status: 'CONFIRMED', confirmedByMemberId: member, confirmedAt: new Date().toISOString(), updatedAt: new Date().toISOString() }).where(eq(stockTransfers.id, id)); }); return this.withItems(id, farmId); }
  private async only(id: string, farmId: string, db = this.databaseService.db) { const [row] = await db.select().from(stockTransfers).where(and(eq(stockTransfers.id, id), eq(stockTransfers.farmId, farmId))).limit(1); if (!row) throw new NotFoundException('Stock transfer not found'); return row; }
  private async withItems(id: string, farmId: string) { const transfer = await this.only(id, farmId); const items = await this.databaseService.db.select().from(stockTransferItems).where(eq(stockTransferItems.stockTransferId, id)).orderBy(asc(stockTransferItems.createdAt)); return { transfer, items }; }
  private validateItems(lines: CreateStockTransferDto['items']) { if (!lines?.length) throw new BadRequestException('Transfer must contain at least one item'); }
  private async assertWarehouse(db: any, farmId: string, id: string) { const [row] = await db.select({ id: warehouses.id }).from(warehouses).where(and(eq(warehouses.id, id), eq(warehouses.farmId, farmId), eq(warehouses.status, 'ACTIVE'))); if (!row) throw new ConflictException('Warehouse must exist and be ACTIVE'); }
  private async validateLines(db: any, farmId: string, lines: CreateStockTransferDto['items']) { for (const line of lines) { const [item] = await db.select({ id: items.id }).from(items).where(and(eq(items.id, line.itemId), eq(items.farmId, farmId))); if (!item) throw new NotFoundException('Transfer item not found'); if (line.lotId) { const [lot] = await db.select({ id: inventoryLots.id }).from(inventoryLots).where(and(eq(inventoryLots.id, line.lotId), eq(inventoryLots.farmId, farmId), eq(inventoryLots.itemId, line.itemId))); if (!lot) throw new NotFoundException('LOT not found'); } if (line.assetId) { const [asset] = await db.select({ id: assets.id }).from(assets).where(and(eq(assets.id, line.assetId), eq(assets.farmId, farmId), eq(assets.itemId, line.itemId))); if (!asset) throw new NotFoundException('ASSET not found'); } } }
}
